### ISSUE TITLE
CBBR final schema

### ISSUE THREAD

**Issue by baolingz** [NYCPlanning/db-cbbr#12]
Below is the proposed schema
```
CREATE TABLE cbbr_submissions (
    unique_id text,
    agency text,
    agencyacro text,
    agyresponsecat text,
    agyresponse text,
    address text,
    streetsegment text,
    streetcross1 text,
    streetcross2 text,
    sitename text,
    borough text,
    bbl text,
    cd text,
    commdist text,
    denominator text,
    explanation text,
    need text,
    priority text,
    refname text,
    request text,
    supporters1 text,
    supporters2 text,
    trackingnum text,
    parent_tracking_code text,
    geo_function text,
    geom geometry
);
```

**Comment by AmandaDoyle** [comment]
@jorgeh01 we need to finalize the new CBBR schema so that Labs can update their app
Here is what I propose
https://docs.google.com/spreadsheets/d/1iG-oecIBoljXxkEvqSiGglu4rug6tBKpzv3aln-g3HE/edit?usp=sharing
Please let us know if you'd like to have input.  Also, if a value in the `former schema` column isn't highlighted that means that I am unsure if that column is in the new dataset or not, and if it is what it should map to.  You guidance here is appreciated

**Comment by jorgeh01** [comment]
@AmandaDoyle I will look this over this week and confirm by Friday. Just to be clear, you want me to confirm if the fields that are not highlight are still part of the dataset?

**Comment by AmandaDoyle** [comment]
Outdated and taken care of
